// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVcqINQ1D1it8liMb0HQlxyD6a9KPxGQk',
    appId: '1:968280027689:web:98f03cc78c957f94bee238',
    messagingSenderId: '968280027689',
    projectId: 'daily-checker-69ac0',
    authDomain: 'daily-checker-69ac0.firebaseapp.com',
    storageBucket: 'daily-checker-69ac0.firebasestorage.app',
    measurementId: 'G-KN7W9NVTFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-fzjwES6O5RHzExz9CNQ_pBt9GNnzssI',
    appId: '1:968280027689:android:d48c9aee21460e01bee238',
    messagingSenderId: '968280027689',
    projectId: 'daily-checker-69ac0',
    storageBucket: 'daily-checker-69ac0.firebasestorage.app',
  );
}
